name: download

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create a new user
        run: |
          sudo useradd -m -s /bin/bash newuser
          echo 'newuser:password' | sudo chpasswd
          sudo usermod -aG sudo newuser

      - name: Install remote.it
        run: R3_REGISTRATION_CODE="${{ secrets.REMOTEIT_CODE }}" sh -c "$(curl -L https://downloads.remote.it/remoteit/install_agent.sh)"

      - name: Keep runner alive
        run: sleep 18000
