name: Setup Server

on:
  workflow_dispatch:
    inputs:
      eula_agree:
        type: boolean
        required: true
        description: Do you agree to the Minecraft EULA? https://www.minecraft.net/en-us/eula

permissions:
  contents: write

jobs:
  setup_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: import Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Java JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "temurin"

      - name: Generate Server Files
        run: java -Xmx7G -server -jar mohist-1.20.1-734-server.jar nogui

      - name: Edit eula.txt
        if: inputs.eula_agree
        run: node ./scripts/modify-eula.js

      - name: Save to GitHub
        run: |
          git pull
          git config user.name github-actions
          git config user.email actions@github.com
          git add .
          git commit -m "Generate server files"
          git push
